config/routes.rb
FatFreeCRM::Application.routes.draw do

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'options'    => 'home#options'
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup
  match 'timeline'   => 'home#timeline',           :as => :timeline
  match 'timezone'   => 'home#timezone',           :as => :timezone
  match 'toggle'     => 'home#toggle'

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put :attach
      post :discard
    end
  end

  resources :campaigns do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :contacts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :leads do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      get  :convert
      post :discard
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end
resources :projects do
end

  resources :tasks do
    collection do
      get  :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get  :search
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :settings
    resources :plugins
  end

  match '/:controller(/:action(/:id))'
end

app/models/project.rb
class Project < ActiveRecord::Base
 attr_accessor :calendar

  belongs_to  :user
  belongs_to  :assignee, :class_name => "User", :foreign_key => :assigned_to
  belongs_to  :completor, :class_name => "User", :foreign_key => :completed_by
  belongs_to  :asset, :polymorphic => true
  has_many    :activities, :as => :subject, :order => 'projects.created_at DESC'
scope :my, lambda { |user|
    includes(:assignee).
    where('(user_id = ? AND assigned_to IS NULL) OR assigned_to = ?', user[:user] || user, user[:user] || user).
    order(user[:order] || 'name ASC').
    limit(user[:limit]) # nil selects all records
  }
 scope :assigned_by, lambda { |user|
    includes(:assignee).
    where('user_id = ? AND assigned_to IS NOT NULL AND assigned_to != ?', user.id, user.id)
  }
# Status based scopes to be combined with the due date and completion time.
  scope :pending,       where('completed_at IS NULL').order('projects.due_at, projects.id')
  scope :assigned,      where('completed_at IS NULL AND assigned_to IS NOT NULL').order('projects.due_at, projects.id')
  scope :completed,     where('completed_at IS NOT NULL').order('projects.completed_at DESC')

  # Due date scopes.
  scope :due_asap,      where("due_at IS NULL AND bucket = 'due_asap'").order('projects.id DESC')
  scope :overdue,       where('due_at IS NOT NULL AND due_at < ?', Time.zone.now.midnight.utc).order('projects.id DESC')
  scope :due_today,     where('due_at >= ? AND due_at < ?', Time.zone.now.midnight.utc, Time.zone.now.midnight.tomorrow.utc).order('projects.id DESC')
  scope :due_tomorrow,  where('due_at >= ? AND due_at < ?', Time.zone.now.midnight.tomorrow.utc, Time.zone.now.midnight.tomorrow.utc + 1.day).order('projects.id DESC')
  scope :due_this_week, where('due_at >= ? AND due_at < ?', Time.zone.now.midnight.tomorrow.utc + 1.day, Time.zone.now.next_week.utc).order('projects.id DESC')
  scope :due_next_week, where('due_at >= ? AND due_at < ?', Time.zone.now.next_week.utc, Time.zone.now.next_week.end_of_week.utc + 1.day).order('projects.id DESC')
  scope :due_later,     where("(due_at IS NULL AND bucket = 'due_later') OR due_at >= ?", Time.zone.now.next_week.end_of_week.utc + 1.day).order('projects.id DESC')

  # Completion time scopes.
  scope :completed_today,      where('completed_at >= ? AND completed_at < ?', Time.zone.now.midnight.utc, Time.zone.now.midnight.tomorrow.utc)
  scope :completed_yesterday,  where('completed_at >= ? AND completed_at < ?', Time.zone.now.midnight.yesterday.utc, Time.zone.now.midnight.utc)
  scope :completed_this_week,  where('completed_at >= ? AND completed_at < ?', Time.zone.now.beginning_of_week.utc , Time.zone.now.midnight.yesterday.utc)
  scope :completed_last_week,  where('completed_at >= ? AND completed_at < ?', Time.zone.now.beginning_of_week.utc - 7.days, Time.zone.now.beginning_of_week.utc)
  scope :completed_this_month, where('completed_at >= ? AND completed_at < ?', Time.zone.now.beginning_of_month.utc, Time.zone.now.beginning_of_week.utc - 7.days)
  scope :completed_last_month, where('completed_at >= ? AND completed_at < ?', (Time.zone.now.beginning_of_month.utc - 1.day).beginning_of_month.utc, Time.zone.now.beginning_of_month.utc)


 def self.find_all_grouped(user, view)
	
    settings = (view == "completed" ? Setting.project_completed : Setting.project_bucket)
    Hash[
      settings.map do |key, value|
        [ key, view == "assigned" ? assigned_by(user).send(key).pending : my(user).send(key).send(view) ]
      end
    ]
  end

 # Returns project totals for each of the views as needed by projects sidebar.
  #----------------------------------------------------------------------------
  def self.totals(user, view = "pending")
    settings = (view == "completed" ? Setting.project_completed : Setting.project_bucket)
    settings.inject({ :all => 0 }) do |hash, key|
      hash[key] = (view == "assigned" ? assigned_by(user).send(key).pending.count : my(user).send(key).send(view).count)
      hash[:all] += hash[key]
      hash
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_filter :require_user
  before_filter :auto_complete, :only => :auto_complete
  before_filter :update_sidebar, :only => :index
  before_filter :set_current_tab, :only => [ :index, :show ]

  # GET /projects
  # GET /projects.xml
  #----------------------------------------------------------------------------
  def index
    @view = params[:view] || "pending"
puts @view

    @projects = Project.find_all_grouped(@current_user, @view)

    respond_to do |format|
      format.html # index.html.haml
      format.xml  { render :xml => @projects }
      format.xls  { send_data @projects.values.flatten.to_xls, :type => :xls }
      format.csv  { send_data @projects.values.flatten.to_csv, :type => :csv }
      format.rss  { render "common/index.rss.builder" }
      format.atom { render "common/index.atom.builder" }
    end
  end
def update_sidebar
    @view = params[:view]
    @view = "pending" unless %w(pending assigned completed).include?(@view)
    @project_total = Project.totals(@current_user, @view)

    # Update filters session if we added, deleted, or completed a project.
    if @project
      update_session do |filters|
        if @empty_bucket  # deleted, completed, rescheduled, or reassigned and need to hide a bucket
          filters.delete(@empty_bucket)
        elsif !@project.deleted_at && !@project.completed_at # created new project
          filters << @project.computed_bucket
        end
      end
    end

    # Create default filters if filters session is empty.
    name = "filter_by_project_#{@view}"
    unless session[name]
      filters = @project_total.keys.select { |key| key != :all && @project_total[key] != 0 }.join(",")
      session[name] = filters unless filters.blank?
    end
  end
 def new
    @project = Project.new
    @view = params[:view] || "pending"
    @users = User.except(@current_user).by_name
    @bucket = Setting.unroll(:project_bucket)[1..-1] 
#---------------------------------------------------------------try----------------------------------
    @category = Setting.unroll(:project_category)
    if params[:related]
      model, id = params[:related].split("_")
      instance_variable_set("@asset", model.classify.constantize.my.find(id))
    end

    respond_to do |format|
      format.js   # new.js.rjs
      format.xml  { render :xml => @project }
    end

  rescue ActiveRecord::RecordNotFound # Kicks in if related asset was not found.
    respond_to_related_not_found(model, :js) if model
  end

 def create
    @project = Project.new(params[:project]) # NOTE: we don't display validation messages for tasks.
    @view = params[:view] || "pending"

    respond_to do |format|
      if @project.save
        update_sidebar if called_from_index_page?
        format.js   # create.js.rjs
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.js   # create.js.rjs
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
def project_filter_checbox(view, filter, count)
    name = "filter_by_project_#{view}"
    checked = (session[name] ? session[name].split(",").include?(filter.to_s) : count > 0)
    onclick = remote_function(
      :url      => { :action => :filter, :view => view },
      :with     => "'filter='+this.value+'&checked='+this.checked",
      :loading  => "$('loading').show()",
      :complete => "$('loading').hide()"
    )
    check_box_tag("filters[]", filter, checked, :onclick => onclick)
  end
end

app/views/projects/_assigned.html.haml
%li[assigned]{ highlightable(dom_id(assigned, :tools)) }
  - unless assigned.category.blank?
    .strip{:class => assigned.category}= t(assigned.category)
  - else
    .strip.white #{t :other}

  .tools{ invisible, :id => dom_id(assigned, :tools) }
    = link_to_project_edit(assigned, bucket) + " | "
    = link_to_discard(assigned) + " | " if shown_on_landing_page?
    = link_to_project_delete(assigned, bucket)

  .indent
    = link_to(assigned.assignee.full_name, user_path(assigned.assignee)) + ": "
    = auto_link h(assigned.name)
    - if assigned.asset_id?
      == #{t :related} #{link_to(h(assigned.asset.name), polymorphic_url(assigned.asset))}
    &ndash;
    %tt
      - if assigned.bucket == "due_asap"
        %span.urgent= t(:project_due_now)

      - elsif assigned.bucket == "due_later"
        = t(:project_due_later)

      - else
        - if assigned.at_specific_time?
          - if assigned.due_at < Time.now
            %span.warn= distance_of_time_in_words(assigned.due_at, Time.now)
            = t(:project_overdue) 
            = l(assigned.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:project_due_in, distance_of_time_in_words(Time.now, assigned.due_at))
            = '(' << l(assigned.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if assigned.due_at < Date.today
            %span.warn= distance_of_time_in_words(assigned.due_at, Time.now) 
            = t(:project_overdue) 
            = assigned.due_at.localtime.strftime('%b %e')
          - elsif assigned.due_at > Date.today
            = t(:project_due_in, distance_of_time_in_words(Time.now, assigned.due_at.localtime.end_of_day))
          - else
            %span.cool= t(:project_due_today)

    - unless assigned.background_info.blank?
      %div
        %dt= h(assigned.background_info)

app/views/projects/_completed.html.haml
%li[completed]{ highlightable(dom_id(completed, :tools)) }
  - unless completed.category.blank?
    .strip{:class => completed.category}= t(completed.category)
  - else
    .strip.white #{t :other}

  .tools{ invisible, :id => dom_id(completed, :tools) }
    - if shown_on_landing_page?
      = link_to_discard(completed) + (@current_user == completed.user ? ' | ' : '')
    = link_to_project_delete(completed, bucket) if @current_user == completed.user

  .indent
    %strike= auto_link h(completed.name)
    - if completed.asset_id?
      == #{t :related} #{link_to(h(completed.asset.name), polymorphic_url(completed.asset))}
    &ndash;
    %tt
      %span.cool
        -# :project_completed_by: "completed {{time_ago}} ago by {{user}}"
        = t(:project_completed_by, :time_ago => distance_of_time_in_words(completed.completed_at, Time.now), :date => completed.completed_at, :user => ((completed.completor.id != @current_user.id) ? link_to(completed.completor.full_name, user_path(completed.completor)) : t(:me)))
    - unless completed.background_info.blank?
      %div
        %dt= h(completed.background_info)

app/views/projects/_create.html.haml
= form_for(@project, :html => one_submit_only(:project), :remote => true) do |f|
  = link_to_close new_project_path + "?view=#{@view}"
  = hidden_field_tag :view, @view
  = hidden_field_tag "project[user_id]", @current_user.id
  = hidden_field_tag "project[asset_id]", "#{@asset.id if @asset}"
  = hidden_field_tag "project[asset_type]", "#{@asset.class if @asset}"
  = render "projects/top_section", :f => f
  .buttonbar
    = f.submit t :create_project
    #{t :or}
    = link_to_cancel new_project_path + "?view=#{@view}"

app/views/projects/_empty.html.haml
#empty
  == #{t(:no_projects, t('no_projects_' + @view))}.
  - if @view != "completed"
    == #{t :feel_free} #{link_to(t(:create_project_small), new_project_path + "?view=#{@view}", :remote => true)}.

app/views/projects/_pending.html.haml
%li[pending]{ highlightable(dom_id(pending, :tools)) }
  - unless pending.category.blank?
    .strip{:class => pending.category}= t(pending.category)
  - else
    .strip.white #{t :other}

  .tools{ invisible, :id => dom_id(pending, :tools) }
    = link_to_project_edit(pending, bucket) + " | "
    = link_to_discard(pending) + " | " if shown_on_landing_page?
    = link_to_project_delete(pending, bucket)

  = check_box_tag dom_id(pending, :complete), 1, false, :onclick => link_to_project_complete(pending, bucket)

  .indentwide
    %label{ :id => dom_id(pending, :name) }
      - if pending.user.id != @current_user.id
        = t(:project_from, link_to(pending.user.full_name, user_path(pending.user))).html_safe << ':'
      = auto_link h(pending.name)
      - if pending.asset_id?
        == #{t :related} #{link_to(h(pending.asset.name), polymorphic_url(pending.asset))}
      &ndash;
    %tt
      - if pending.bucket == "due_asap"
        %span.urgent= t(:project_due_now)

      - elsif pending.bucket == "due_later"
        = t(:project_due_later)

      - else
        - if pending.at_specific_time?
          - if pending.due_at < Time.now
            %span.warn= distance_of_time_in_words(pending.due_at, Time.now)
            = t(:project_overdue)
            = l(pending.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:project_due_in, distance_of_time_in_words(Time.now, pending.due_at))
            = '(' << l(pending.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if pending.due_at < Date.today
            %span.warn= distance_of_time_in_words(pending.due_at, Time.now)
            = t(:project_overdue)
            = pending.due_at.localtime.strftime('%b %e')
          - elsif pending.due_at > Date.today
            = t(:project_due_in, distance_of_time_in_words(Time.now, pending.due_at.localtime.end_of_day))
          - else
            %span.cool= t(:project_due_today)

    - unless pending.background_info.blank?
      %div
        %dt= h(pending.background_info)

app/views/projects/_selector.html.haml
%table{ :cellpadding => 3, :cellspacing => 0, :style => "width: 100%; margin: 2px 0px 10px 0px" }
  %tr
    %td{ :class => "selector left " + (@view == "pending" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{projects_path}') }
      #{t :pending_tab}
    %td{ :class => "selector " + (@view == "assigned" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{url_for(:action => :index, :view => "assigned")}') }
      #{t :assigned_tab}
    %td{ :class => "selector right " + (@view == "completed" ? "on" : "off"), :width => "33%", :onclick => %Q(document.location.href='#{url_for(:action => :index, :view => "completed")}') }
      #{t :completed_tab}

app/views/projects/_sidebar_index.html.haml
.filters#filters
  = render "selector"
  - if @view == "pending" || @view == "assigned"
    - Setting.unroll(:project_bucket).each do |value, key|
      .check_box{:style => "border-bottom: 1px silver dotted;"}
        %div{:style => "float:right;"}
          = @project_total[key]
        = project_filter_checbox(@view, key, @project_total[key]) << " " << t(value)
  - else # @view == "completed"
    - Setting.unroll(:project_completed).each do |value, key|
      .check_box{:style => "border-bottom: 1px silver dotted;"}
        %div{:style => "float:right;"}
          = @project_total[key]
        = project_filter_checbox(@view, key, @project_total[key]) << " " << t(value)
  .check_box
    %div{:style => "float:right;"}
      %b= @project_total[:all]
    %b== #{t(:total_projects, t(@view + '_projects'))}

app/views/projects/_title.html.haml
.title_tools
  = link_to_inline(:create_project, url_for(:action => :new, :view => @view), :text => t(:create_project))
.title#title
  = (@view == "assigned" ? t(:assigned_projects) : t(:projects))
  = image_tag("loading.gif", :size => "16x16", :id => "loading", :style => "display: none;")

.remote#options{ hidden }
.remote#create_task{ hidden }

app/views/projects/_top_section.html.haml
.section
  %table
    %tr
      %td(colspan="5")
        .label.top.req #{t :name}:
        = f.text_field :name, :style => "width:500px"
    %tr
      %td
        .label.req #{t :due}:
        - bucket = (params[:bucket].blank? ? @project.bucket : params[:bucket]) || "due_asap"
        - if @project.bucket != "specific_time"
          = f.select :bucket, @bucket, { :selected => bucket.to_sym }, { :style => "width:160px;", :onchange => "crm.flip_calendar(this.value)" }
          = f.text_field :calendar, :style => "width:160px; display:none;", :autocomplete => :off
        - else
          = f.select :bucket, @bucket, { :selected => :specific_time }, { :style => "width:160px; display:none;", :onchange => "crm.flip_calendar(this.value)" }
          = f.text_field :calendar, :value => (Setting.project_calendar_with_time ? l(f.object.due_at.localtime, :format => :mmddyyyy_hhmm) : l(f.object.due_at.to_date, :format => :mmddyyyy)), :style => "width:160px;", :autocomplete => :off
      %td= spacer
      %td
        .label.req #{t :assign_to}:
        = collection_select :project, :assigned_to, @users, :id, :full_name, { :include_blank => t(:myself) }, { :style => "width:160px", :disabled => @project.assigned_to == @current_user.id }
      %td= spacer
      %td
        .label.req #{t :category}:
        = f.select :category, @category, { :selected => @project.category.blank? ? nil : @project.category.to_sym, :include_blank => t(:select_blank) }, { :style => "width:160px" }

    - if Setting.background_info && Setting.background_info.include?(:project)
      %tr
        %td(colspan="5")
          .label= t(:extra_info).capitalize << ':'
          = f.text_area :background_info, :style =>"width:500px", :rows => 3

    = hook(:project_top_section_bottom, self, :f => f)

app/views/projects/index.html.haml
= styles_for :project

- if @view == "completed"
  - buckets = Setting.unroll(:project_completed)
  .title
    = t(:completed_projects)
    = image_tag("loading.gif", :size => "16x16", :id => "loading", :style => "display: none;")
- else
  - buckets = Setting.unroll(:project_bucket)
  = render "title"

.log#projects
  - buckets.each do |value, key|
    %div{ hidden_if(filtered_out?(@view, key)), :id => "list_#{key}" }
      %h3{:class => key}= t(value)
      .bucket{:id => key}= render :partial => @view, :collection => @projects[key] || [], :locals => { :bucket => key }
  - if @projects.values.flatten.blank?
    = render "empty"